.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "LOVE" "" "February 2020" "" ""
.
.SH "NAME"
\fBlove\fR
.
.SH "NAME"
.
.nf

love \- motivanal lizard in terminal
.
.fi
.
.SH "DESCRIPTION"
.
.nf

A simple program that tells you are loved
.
.fi
.
.SH "SYNOPSIS"
.
.nf

\-v, \-\-version
.
.fi
.
.SH "EXAMPLE"
.
.nf

love \-v
.
.fi
.
.SH "SOURCE"
.
.nf

https//:github\.com/tibthink/love
.
.fi
.
.SH "AUTHOR"
.
.nf

TIBTHINK
.
.fi

